server:
  port: 8080


spring:
    datasource:
        name: postgresql
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          filters: stat
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/search-engine
          username: root
          password: local-test-pwd
          initial-size: 1
          min-idle: 1
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    jpa:
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms # 超时时间
      lettuce:
        pool:
          max-active: 200 #连接池最大连接数（使用负值表示没有限制）
          max-idle: 20 # 连接池中的最大空闲连接
          min-idle: 5 #连接池中的最小空闲连接
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）